version: '3'

services:
  chatservice:
    build: .
    container_name: chatservice_app1
    volumes:
      - .:/Users/superlogica/Development/full-cycle/chatservice
    ports:
      - "8081:8080"
      - "50052:50051"
    networks:
      - fcexperience

  mysql:
    image: mysql:8
    container_name: mysql1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chat_test
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306  
    volumes:
      - .docker/mysql:/var/lib/mysql
    networks:
      - fcexperience

networks:
  fcexperience:
    external:
      name: fcexperience