GET http://localhost:3000/api/hello

@token = eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..XnskWOEMEV-7teRh.Kfx1uSJGTBQzhMdy_gaDlCNz_Lz9UvSeKBCMBPHdKOZmN-WoZZRkOrFwmdbBDfKjRg7Y48VnP_9-K5xkUP4H6nGeCvc9ovRvuKlGFKm2ja_E3CjYjGLHRFLjrcYIu3qb9YPNYIZ41leztsY20HPbtQ7lyxUjKYwjDKvU3e59hvg8QNjc3dQyglaCvzs.TIHDzzl-FrxwwH3hKFr1Wg
###
POST http://localhost:3000/api/chats
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "message": "How long does a cat live?"
}

###
GET http://localhost:3000/api/chats
Authorization: Bearer {{token}}

###
@chatId = e3dcc475-6de9-4146-9413-5c931a644bb3

GET http://localhost:3000/api/chats/{{chatId}}/messages
Authorization: Bearer {{token}}

###
POST http://localhost:3000/api/chats/{{chatId}}/messages
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "message": "Whats yuour name?"
}

###
@messageId = 79ca19fc-8165-45a3-806d-762d5eee308c
GET http://host.docker.internal:3000/api/messages/{{messageId}}/events
Authorization: Bearer {{token}}

###
POST http://localhost:3000/api/generate-token
Content-Type: application/json

{

}

###
GET http://localhost:3000/api/event-stream